### ISSUE TITLE
Multiple Class version

### ISSUE THREAD

**Issue by abhiray92** [saimj7/Video-Classification-in-Real-Time#2]
The model is built upon 2 classes, I downloaded the UCF-101 dataset and moved it into a the 'dataset' folder. 

1. What is to be put in Class 1 and Class 2 folder?

2. I have a dataset of videos for over 2000 classes and the metadata the videos mapped with the actions. How can I incorporate my dataset with this model?

**Comment by saimj7** [comment]
Hi @abhiray92 

Currently, the model only supports 2 classes at a time (you can only classify/recognize 2 classes). So you just need to place your desired 'videos' into class 1 and 2 folders respectively. Running `Preprocessing.ipynb` block by block will get you initialized with the folders.
