### ISSUE TITLE
Library and Python Version?

### ISSUE THREAD

**Issue by tomatopuree** [saimj7/Video-Classification-in-Real-Time#3]
Hi there!

Great repo, just a quick question: What are the library versions you are using?

Namely, I would need the version numbers for the libraries listed in your requirements.txt, alongside your python version. (I will paste them below)

pandas
numpy
opencv-python
matplotlib
tqdm
keras
tensorflow-gpu

Thank you and great work!

**Comment by saimj7** [comment]
Hi, thanks! Updated the requirements.txt
